classes:
- system.linux.system.repo.ubuntu
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.salt.minion.cert.k8s_server
- system.mysql.client
- system.mysql.client.database.grafana
- system.reclass.storage.salt
- system.reclass.storage.system.kubernetes_control_cluster
- cluster.virtual-mcp11-k8s-calico.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://gerrit.mcp.mirantis.net/salt-models/mcp-virtual-lab.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$WV0P1shnoDh2gI/Z$22/Bcd7ffMv0jDlFpT63cAU4PiXHz9pjXwngToKwqAsgoeK4HNR3PiKaushjxp3JsQ8hNoJmAC6TxzVqfV8WH/"
    salt_master_host: ${_param:infra_config_deploy_address}
  reclass:
    storage:
      node:
        kubernetes_compute_node01:
          name: ${_param:kubernetes_compute_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.compute
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_compute_node01_address}
        kubernetes_compute_node02:
          name: ${_param:kubernetes_compute_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.compute
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_compute_node02_address}
        prx_node:
          name: ${_param:kubernetes_proxy_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.monitoring.proxy
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_proxy_node01_address}
        docker_swarm_node01:
          name: ${_param:docker_swarm_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - service.galera.master.cluster
          - cluster.${_param:cluster_name}.swarm.master
          - cluster.${_param:cluster_name}.monitoring.client
          - cluster.${_param:cluster_name}.monitoring.server
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:docker_swarm_node01_address}
            keepalived_vip_priority: 100
            mysql_cluster_role: master
        docker_swarm_node02:
          name: ${_param:docker_swarm_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - service.galera.slave.cluster
          - cluster.${_param:cluster_name}.swarm.slave
          - cluster.${_param:cluster_name}.monitoring.server
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:docker_swarm_node02_address}
            keepalived_vip_priority: 101
            mysql_cluster_role: slave
        docker_swarm_node03:
          name: ${_param:docker_swarm_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - service.galera.slave.cluster
          - cluster.${_param:cluster_name}.swarm.slave
          - cluster.${_param:cluster_name}.monitoring.server
          params:
            salt_master_host: ${_param:infra_config_deploy_address}
            linux_system_codename: xenial
            single_address: ${_param:docker_swarm_node03_address}
            keepalived_vip_priority: 102
            mysql_cluster_role: slave
