classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.linux.system.repo.docker
- system.salt.minion.cert.etcd_server
- system.kubernetes.master.cluster
- cluster.virtual-mcp11-k8s-contrail.kubernetes.compute
- cluster.overrides
parameters:
  _param:
    keepalived_vip_interface: vhost0
    keepalived_vip_virtual_router_id: 60
  etcd:
    server:
      source:
        engine: docker_hybrid
      ssl:
        enabled: true
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  kubernetes:
    master:
      etcd:
        ssl:
          enabled: true
      network:
        etcd:
          ssl:
            enabled: true
      namespace:
        netchecker:
          enabled: true
      namespace:
        netchecker:
          enabled: ${_param:kubernetes_netchecker_enabled}
      addons:
        helm:
          enabled: ${_param:kubernetes_helm_enabled}
        netchecker:
          enabled: ${_param:kubernetes_netchecker_enabled}
          agent_image: ${_param:kubernetes_netchecker_agent_image}
          server_image: ${_param:kubernetes_netchecker_server_image}
        virtlet:
          enabled: ${_param:kubernetes_virtlet_enabled}
          namespace: kube-system
          hosts:
          - ${_param:kubernetes_compute_node01_hostname}
          - ${_param:kubernetes_compute_node02_hostname}
          image: ${_param:kubernetes_netchecker_server_image}
        kube_network_manager:
          enabled: ${_param:kubernetes_virtlet_image}
      network:
        engine: opencontrail
        public_ip_range: 185.22.97.128/26
        public_network: default-domain:default-project:Public
        private_ip_range: 10.150.0.0/16
        config:
          api:
            address: ${_param:opencontrail_control_address}
